name: hello-world
on: push
jobs:
  my-job:
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - name: my-step
        run: |
          $env:cache_dir = "${{ env.CACHE_DIR }}"
          $env:cache_dir
          echo "Hello World!"
